name: 'Entrega de Pudim'
on:
  push:
jobs:
  entrega-de-pudim:
    runs-on: ubuntu-latest
    if: contains(github.ref, 'master')
    steps:
      - uses: actions/checkout@v1

      - name: Embalando o Pudim
        run: docker build -t pudim:latest .

      - name: Colocando o Lacre na Embalagem do Pudim
        run: docker tag pudim:latest fidelissauro/pudim:latest

      - name: Pegando o celular do motoboy
        uses: docker/login-action@v1
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD}}

      - name: Mandando o Motoboy Levar o Pudim
        run: docker push fidelissauro/pudim:latest